### ISSUE TITLE
Login user verification

### ISSUE THREAD

**Issue by jebisseth-uit** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#132]
Get username and password from html, query database to check if it's a match, give feedback to user. 

For future, the feedback should be able to send data such as if the user is logged in and what user.

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **3**, the median vote was **2.5** story points.
