### ISSUE TITLE
Admin - change group memberst usertype

### ISSUE THREAD

**Issue by jebisseth-uit** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#133]
The admin in a usergroup should be able to change the members of the group to admin or normal user using a dropdown next in the "Gruppeadministrasjon"

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **5**, the median vote was **5** story points.
