### ISSUE TITLE
Implement functionality for creating usergroup and become admin for that group

### ISSUE THREAD

**Issue by carlosreiakvam-uit** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#137]
User creates usergroup and becomes admin for the usergroup

- Fetch own userid from session
- Input name for group
- Check if name allready exists
- Else:
  - Create usergroup in table usergroup
  - Add own user to new usergroup - "userHasUsergroup"
  - Change usertype to admin in table "userHasUsergroup"

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **5**, the median vote was **4** story points.
