### ISSUE TITLE
user specific views (gruppeadministrasjons-side)

### ISSUE THREAD

**Issue by SillyOlly** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#138]
User with no usergroup: "Opprett gruppe"

Admin user: "Inviter bruker" + " Brukere i gruppen"

Normal user with usergroup: Nothing

Denne er i stor grad løst med 139 husker jeg ikke feil!

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **5**, the median vote was **4** story points.

**Comment by jebisseth-uit** [comment]
Tar denne med meg og lukker den sammen med resten av usergroup-issuene
