### ISSUE TITLE
Change and organize profile and group administration pages

### ISSUE THREAD

**Issue by carlosreiakvam-uit** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#139]
- [ DONE ] Change title to "Register"

- [ DONE ] Remove register link when logged in

- [ DONE ] Group admin page

- [ DONE ] Add user to group only show for admins

create group
- [ DONE ] show all users in current usergroup (but only hardcoded)

- [ DONE ]  Profile page
Remove table displaying all users
Functionality for deleting self from usergroups
User-info
Invitation thingy displaying

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **2**, the median vote was **1.5** story points.
