### ISSUE TITLE
Edit-option for ingredient price

### ISSUE THREAD

**Issue by carlosreiakvam-uit** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#141]

**Comment by carlosreiakvam-uit** [comment]
In ingredient list in page "ingredienser"

- Implement edit button 
- Implement delete button

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **3**, the median vote was **3** story points.
