### ISSUE TITLE
Option to edit an ingredient

### ISSUE THREAD

**Issue by sanehint** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#164]

**Comment by sanehint** [comment]
Bør egentlig kun kunne endre hvor stor mengde man HAR i beholdningen av dette.  Mulighet for å redigere ingrediens. OBS! Dette vil potensielt forårsake mange endringer mange plasser dersom det endres f.eks navn - da bør i tilfelle en ny ingrediens heller opprettes. Ved å kunne endre også hva slags mengdeenhet, etc også, blir det potensielt problemer.

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **5**, the median vote was **5** story points.
