### ISSUE TITLE
Add recipe in meny/dinner planner 

### ISSUE THREAD

**Issue by sanehint** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#166]
Legge til oppskrift i meny/middagsplanleggeren  - med alle de mulighetene det innebærer. HVILKE KRAV??? Sjekk i prosjektbeskrivelsen!

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **13**, the median vote was **13** story points.

**Comment by sanehint** [comment]
Løs dette med kommentar som i #167
