### ISSUE TITLE
Generating report (costs, consume)

### ISSUE THREAD

**Issue by sanehint** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#169]
Rapportgenerering: kostnadsoversikt per uke, per måned, på grunnlag av middagsplanlegger over. Forbruk av ingredienser.

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **20**, the median vote was **20** story points.

**Comment by jebisseth-uit** [comment]
Lager egne mapper/blueprint etc for rapporter
