### ISSUE TITLE
Register recipe - if one recipe (dish) is registered, and press the button again, it double register. Also, might crash. Bug fix. 

### ISSUE THREAD

**Issue by sanehint** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#172]
Bug: Når man trykker registrere en rett, og skal gjøre på nytt. Må ta en sjekk på om den eksisterer, så oppdatere.
må også få opp i liste hva som retten består av. 
Oppskriftlista kræsjer også da

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **5**, the median vote was **5** story points.
