### ISSUE TITLE
Remove the selection of group when the user register him/herself

### ISSUE THREAD

**Issue by sanehint** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#176]

**Comment by sanehint** [comment]
-fjerne at man velger hvilken gruppe man registerer seg med og brukertype når man registrer seg første gangen

**Comment by SillyOlly** [comment]
Estimated in [Planning/Refinement Room](https://play-game.scrumpypoker.com/#/room/rulikzlvyrhe) to **2**, the median vote was **2** story points.
