### ISSUE TITLE
Add recipe backend python

### ISSUE THREAD

**Issue by SillyOlly** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#21]

**Comment by SillyOlly** [comment]
**As a** user
 **I need** to add a recipe
 **So that** it can be used to set up a weekly menu
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by Stianlyng** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Systemutvikling---Ne-3-Muchies-620becd4cddc16001522f7c0/issues/Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-/21?planning-poker) with ZenHub @carlosreiakvam-uit @jebisseth-uit @sanehint @SillyOlly
