### ISSUE TITLE
Create logic for generating weekly menu

### ISSUE THREAD

**Issue by SillyOlly** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#24]
**As a** user
 **I need** to create a weekly menu 
 **So that** we know what to eat/serve this week
   
 ### Details and Assumptions
The weekly menu consists of recipes from the database
The number of portions of each recipe is included
It should be some logical solution for when a new week begins it resets
The weekly menu might be stored so it can easily be used again
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I have created a weekly menu
 When I want to see the weekly menu
 Then it should be easy to find and see an overview of the current weeks weekly menu
 ```

**Comment by carlosreiakvam-uit** [comment]
Estimated in [Munchies](https://play-game.scrumpypoker.com/#/room/kyjaoythgaxx) to **13**, the average vote was **13.7** story points.
