### ISSUE TITLE
Register ingrediens (backend python)

### ISSUE THREAD

**Issue by Stianlyng** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#3]

**Comment by carlosreiakvam-uit** [comment]
**As a** user
**I need** register ingredients
**So that** they can be used for making recipes
### Details and Assumptions
* [document what you know]

### Acceptance Criteria

```gherkin
Given [some context]
When [certain action is taken]
Then [the outcome of action is observed]
```

**Comment by Stianlyng** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Systemutvikling---Ne-3-Muchies-620becd4cddc16001522f7c0/issues/Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-/3?planning-poker) with ZenHub @carlosreiakvam-uit @jebisseth-uit @sanehint @SillyOlly
