### ISSUE TITLE
css add recipe

### ISSUE THREAD

**Issue by SillyOlly** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#39]
**As a** [role]  
 **I need** [function]  
 **So that** [benefit]  
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria

 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by carlosreiakvam-uit** [comment]
Estimated in [Munchies](https://play-game.scrumpypoker.com/#/room/kyjaoythgaxx) to **1**, the average vote was **1.3** story points.
