### ISSUE TITLE
Register ingredient - fetch ID from "usergroup_has_ingredient"

### ISSUE THREAD

**Issue by jebisseth-uit** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#56]
When registering a new ingredient, we need to fetch corresponding ID (new or existing" from table "usergroup_has_ingredient"

**Comment by carlosreiakvam-uit** [comment]
Estimated in [Munchies](https://play-game.scrumpypoker.com/#/room/kyjaoythgaxx) to **3**, the average vote was **3** story points.
