### ISSUE TITLE
Register user - fetch usertypes from DB

### ISSUE THREAD

**Issue by jebisseth-uit** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#61]
Need to fetch available usertypes when registering new user

**Comment by carlosreiakvam-uit** [comment]
Estimated in [Munchies](https://play-game.scrumpypoker.com/#/room/kyjaoythgaxx) to **3**, the average vote was **3.2** story points.

**Comment by jebisseth-uit** [comment]
Deprecated by issue #87
