### ISSUE TITLE
Create bootstrap html for ingredients administration

### ISSUE THREAD

**Issue by jebisseth-uit** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#78]
Owner (group) need to be able to edit own ingredients (price/unit)

**Comment by carlosreiakvam-uit** [comment]
Estimated in [Munchies](https://play-game.scrumpypoker.com/#/room/kyjaoythgaxx) to **5**, the average vote was **4** story points.
