### ISSUE TITLE
make testdata redundant for database to work

### ISSUE THREAD

**Issue by carlosreiakvam-uit** [Gruppe-Munchies/Matplanlegger---Systemutvikling-Ne-3--Munchies-#92]
**As a** developer
 **I need** to test local db as easily as possible  
 **So that** misconceptions are kept to a minimal
   
 ### Details and Assumptions
127.0.0.1:5000/testdata has to run in order for queries to work. Needs a fix.
Possibly put whatever is in testada into sql file?

**Comment by Stianlyng** [comment]
Sett litt på det, kan du utdype hva du tenker? Litt usikker på hva issuen er

Det ser i så fall ut som det funker greit, hos meg. @carlosreiakvam-uit
